CREATE TABLE IF NOT EXISTS players (
  id VARCHAR(36) PRIMARY KEY,
  discord_user_id VARCHAR(32) NOT NULL UNIQUE,
  handle VARCHAR(32) NOT NULL,
  current_era ENUM('DIAL_UP','BULLETIN_RELAY','EARLY_INTERNET','MODERN_GRID') NOT NULL DEFAULT 'DIAL_UP',
  reputation INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS player_nodes (
  id VARCHAR(36) PRIMARY KEY,
  player_id VARCHAR(36) NOT NULL,
  node_name VARCHAR(64) NOT NULL,
  archetype ENUM('RELAY_NODE','VAULT_NODE','MARKET_NODE','HUNTER_NODE','GHOST_NODE') NOT NULL,
  integrity INT NOT NULL DEFAULT 100,
  bandwidth INT NOT NULL DEFAULT 1,
  storage INT NOT NULL DEFAULT 1,
  processing INT NOT NULL DEFAULT 1,
  security INT NOT NULL DEFAULT 1,
  credits INT NOT NULL DEFAULT 100,
  data INT NOT NULL DEFAULT 25,
  cycles INT NOT NULL DEFAULT 5,
  parts INT NOT NULL DEFAULT 10,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_player_nodes_player FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS scan_results (
  id VARCHAR(36) PRIMARY KEY,
  player_id VARCHAR(36) NOT NULL,
  discovery_type ENUM('ABANDONED_RELAY','VULNERABLE_NODE','ARCHIVE_CACHE','FACTION_CONTRACT') NOT NULL,
  threat_level INT NOT NULL,
  reward_hint VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_scan_results_player FOREIGN KEY (player_id) REFERENCES players(id)
);
